### ISSUE TITLE
关于工作

### ISSUE THREAD

**Issue by mmmmmmmxl** [MeYoung/pact_demo#1]
很抱歉用这样的方式打扰到您，
看了您关于用例管理的博文，找了您的github，
不知您对哔哩哔哩科技(坐标：上海)的测试工具开发相关的工作是否感兴趣。
如果您感兴趣，麻烦您回复我一个联系方式，
如果您不感兴趣，十分抱歉打扰到您，请关闭这个issue。

**Comment by MeYoung** [comment]
感谢！ 但坐标不合适。
